[tool.ruff.lint.isort.sections]
sqliteimport = ["sqliteimport"]

[tool.ruff.lint.isort]
section-order = [
    "future",
    "standard-library",
    "sqliteimport",  # <-- Add this above 'third-party'
    "third-party",
    "first-party",
    "local-folder",
]
