# This file is a part of sqliteimport <https://github.com/kurtmckee/sqliteimport>
# Copyright 2024-2025 Kurt McKee <contactme@kurtmckee.org>
# SPDX-License-Identifier: MIT

import shutil

import click

from . import PACKAGE_DIRECTORY
from . import STATS


@click.command()
def clean() -> None:
    """
    Erase files and directories generated by performance testing script.
    """

    for path in (PACKAGE_DIRECTORY, STATS):
        if path.is_dir():
            shutil.rmtree(path)
