name: "✨ Prep release"

on:
  workflow_dispatch:
    inputs:
      version:
        description: "The new version"
        type: "string"
        required: true

jobs:
  prep-release:
    name: "Prep release v${{ inputs.version }}"

    strategy:
      matrix:
        include:
          - tox-label-create-changes: "prep-release"
            branch-name: "release/$VERSION"
            commit-title: "Update project metadata"
            pr-base: "releases"
            pr-title: "Release v$VERSION"

    uses: "kurtmckee/github-workflows/.github/workflows/create-pr.yaml@dd13826c87b7c607a907142c9cb9a0e9a7ee6c46" # v1.1
    with:
      config: "${{ toJSON(matrix) }}"
      version: "${{ inputs.version }}"
